name: "crop_doctor"
version: "1.0.0+1"
publish_to: none
environment:
  sdk: "^3.5.3"
description: A new Flutter project.
dependencies:
  animated_introduction: "^1.0.4"
  encrypt: "^5.0.3"
  flex_seed_scheme: "^3.4.1"
  flutter:
    sdk: flutter
  flutter_staggered_animations: "^1.1.1"
  get: "^4.6.6"
  get_storage: "^2.1.1"
  google_fonts: "^6.2.1"
  lottie: "^3.1.3"
  material_symbols_icons: "^4.2785.1"
  package_info_plus: "^8.0.3"
  provider: "^6.1.2"
  random_person_data: "^1.0.1"
dev_dependencies:
  flutter_lints: "^4.0.0"
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: "^1.0.4"
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - google_fonts/
